
const EnumMonth = {
	JAN: 'January',
	FEB: 'February',
	MAR: 'March',
	APR: 'April',
	MAY: 'May',
	JUN: 'June',
	JUL: 'July',
	AUG: 'August',
	SEP: 'September',
	OCT: 'October',
	NOV: 'November',
	DEC: 'December'
}

const EnumIndustry = {
	AGR: 'Agriculture',
	ART: 'Art',
	CONS: 'Construction',
	CORP: 'Corporate',
	EDU: 'Education',
	FIN: 'Finance',
	GOOD: 'Goods',
	GOV: 'Government',
	HLTH: 'Health',
	LEG: 'Legal',
	MAN: 'Manufacturing',
	MED: 'Media',
	ORG: 'Organization',
	REC: 'Recreation',
	SERV: 'Service',
	TECH: 'Tech',
	TRAN: 'Transportation',
	OTHER: 'Other'
}

const EnumDegreeType = {
	ASSOCIATE: 'Associate\'s degree',
	BACHELOR: 'Bachelor\'s degree',
	MASTER: 'Master\'s degree',
	DOCTORAL: 'Doctoral degree',
	PROFESSIONAL: 'Professional degree',
	OTHER: 'Other'
}

const EnumMajor = {
	1: `Accounting`,
	2: `Actuarial Science`,
	3: `Advertising`,
	4: `Aerospace Engineering`,
	5: `African Languages, Literatures, and Linguistics`,
	6: `African Studies`,
	7: `African-American Studies`,
	8: `Agricultural Business and Management`,
	9: `Agricultural Economics`,
	10: `Agricultural Education`,
	11: `Agricultural Journalism`,
	12: `Agricultural Mechanization`,
	13: `Agricultural Technology Management`,
	14: `Agricultural/Biological Engineering and Bioengineering`,
	15: `Agriculture`,
	16: `Agronomy and Crop Science`,
	17: `Air Traffic Control`,
	18: `American History`,
	19: `American Literature`,
	20: `American Sign Language`,
	21: `American Studies`,
	22: `Anatomy`,
	23: `Ancient Studies`,
	24: `Animal Behavior and Ethology`,
	25: `Animal Science`,
	26: `Animation and Special Effects`,
	27: `Anthropology`,
	28: `Applied Mathematics`,
	29: `Aquaculture`,
	30: `Aquatic Biology`,
	31: `Arabic`,
	32: `Archeology`,
	33: `Architectural Engineering`,
	34: `Architectural History`,
	35: `Architecture`,
	36: `Art`,
	37: `Art Education`,
	38: `Art History`,
	39: `Art Therapy`,
	40: `Artificial Intelligence and Robotics`,
	41: `Asian-American Studies`,
	42: `Astronomy`,
	43: `Astrophysics`,
	44: `Athletic Training`,
	45: `Atmospheric Science`,
	46: `Automotive Engineering`,
	47: `Aviation`,
	48: `Bakery Science`,
	49: `Biblical Studies`,
	50: `Biochemistry`,
	51: `Bioethics`,
	52: `Biology`,
	53: `Biomedical Engineering`,
	54: `Biomedical Science`,
	55: `Biopsychology`,
	56: `Biotechnology`,
	57: `Botany/Plant Biology`,
	58: `Business Administration/Management`,
	59: `Business Communications`,
	60: `Business Education`,
	61: `Canadian Studies`,
	62: `Caribbean Studies`,
	63: `Cell Biology`,
	64: `Ceramic Engineering`,
	65: `Ceramics`,
	66: `Chemical Engineering`,
	67: `Chemical Physics`,
	68: `Chemistry`,
	69: `Child Care`,
	70: `Child Development`,
	71: `Chinese`,
	72: `Chiropractic`,
	73: `Church Music`,
	74: `Cinematography and Film/Video Production`,
	75: `Circulation Technology`,
	76: `Civil Engineering`,
	77: `Classics`,
	78: `Clinical Psychology`,
	79: `Cognitive Psychology`,
	80: `Communication Disorders`,
	81: `Communications Studies/Speech Communication and Rhetoric`,
	82: `Comparative Literature`,
	83: `Computer and Information Science`,
	84: `Computer Engineering`,
	85: `Computer Graphics`,
	86: `Computer Systems Analysis`,
	87: `Construction Management`,
	88: `Counseling`,
	89: `Crafts`,
	90: `Creative Writing`,
	91: `Criminal Science`,
	92: `Criminology`,
	93: `Culinary Arts`,
	94: `Dance`,
	95: `Data Processing`,
	96: `Dental Hygiene`,
	97: `Developmental Psychology`,
	98: `Diagnostic Medical Sonography`,
	99: `Dietetics`,
	100: `Digital Communications and Media/Multimedia`,
	101: `Drawing`,
	102: `Early Childhood Education`,
	103: `East Asian Studies`,
	104: `East European Studies`,
	105: `Ecology`,
	106: `Economics`,
	107: `Education`,
	108: `Education Administration`,
	109: `Education of the Deaf`,
	110: `Educational Psychology`,
	111: `Electrical Engineering`,
	112: `Elementary Education`,
	113: `Engineering Mechanics`,
	114: `Engineering Physics`,
	115: `English`,
	116: `English Composition`,
	117: `English Literature`,
	118: `Entomology`,
	119: `Entrepreneurship`,
	120: `Environmental Design/Architecture`,
	121: `Environmental Science`,
	122: `Environmental/Environmental Health Engineering`,
	123: `Epidemiology`,
	124: `Equine Studies`,
	125: `Ethnic Studies`,
	126: `European History`,
	127: `Experimental Pathology`,
	128: `Experimental Psychology`,
	129: `Fashion Design`,
	130: `Fashion Merchandising`,
	131: `Feed Science`,
	132: `Fiber, Textiles, and Weaving Arts`,
	133: `Film`,
	134: `Finance`,
	135: `Floriculture`,
	136: `Food Science`,
	137: `Forensic Science`,
	138: `Forestry`,
	139: `French`,
	140: `Furniture Design`,
	141: `Game Design`,
	142: `Gay and Lesbian Studies`,
	143: `Genetics`,
	144: `Geography`,
	145: `Geological Engineering`,
	146: `Geology`,
	147: `Geophysics`,
	148: `German`,
	149: `Gerontology`,
	150: `Government`,
	151: `Graphic Design`,
	152: `Health Administration`,
	153: `Hebrew`,
	154: `Hispanic-American, Puerto Rican, and Chicano Studies`,
	155: `Historic Preservation`,
	156: `History`,
	157: `Home Economics`,
	158: `Horticulture`,
	159: `Hospitality`,
	160: `Human Development`,
	161: `Human Resources Management`,
	162: `Illustration`,
	163: `Industrial Design`,
	164: `Industrial Engineering`,
	165: `Industrial Management`,
	166: `Industrial Psychology`,
	167: `Information Technology`,
	168: `Interior Architecture`,
	169: `Interior Design`,
	170: `International Agriculture`,
	171: `International Business`,
	172: `International Relations`,
	173: `International Studies`,
	174: `Islamic Studies`,
	175: `Italian`,
	176: `Japanese`,
	177: `Jazz Studies`,
	178: `Jewelry and Metalsmithing`,
	179: `Jewish Studies`,
	180: `Journalism`,
	181: `Kinesiology`,
	182: `Korean`,
	183: `Land Use Planning and Management`,
	184: `Landscape Architecture`,
	185: `Landscape Horticulture`,
	186: `Latin American Studies`,
	187: `Library Science`,
	188: `Linguistics`,
	189: `Logistics Management`,
	190: `Management Information Systems`,
	191: `Managerial Economics`,
	192: `Marine Biology`,
	193: `Marine Science`,
	194: `Marketing`,
	195: `Mass Communication`,
	196: `Massage Therapy`,
	197: `Materials Science`,
	198: `Mathematics`,
	199: `Mechanical Engineering`,
	200: `Medical Technology`,
	201: `Medieval and Renaissance Studies`,
	202: `Mental Health Services`,
	203: `Merchandising and Buying Operations`,
	204: `Metallurgical Engineering`,
	205: `Microbiology`,
	206: `Middle Eastern Studies`,
	207: `Military Science`,
	208: `Mineral Engineering`,
	209: `Missions`,
	210: `Modern Greek`,
	211: `Molecular Biology`,
	212: `Molecular Genetics`,
	213: `Mortuary Science`,
	214: `Museum Studies`,
	215: `Music`,
	216: `Music Education`,
	217: `Music History`,
	218: `Music Management`,
	219: `Music Therapy`,
	220: `Musical Theater`,
	221: `Native American Studies`,
	222: `Natural Resources Conservation`,
	223: `Naval Architecture`,
	224: `Neurobiology`,
	225: `Neuroscience`,
	226: `Nuclear Engineering`,
	227: `Nursing`,
	228: `Nutrition`,
	229: `Occupational Therapy`,
	230: `Ocean Engineering`,
	231: `Oceanography`,
	232: `Operations Management`,
	233: `Organizational Behavior Studies`,
	234: `Painting`,
	235: `Paleontology`,
	236: `Pastoral Studies`,
	237: `Peace Studies`,
	238: `Petroleum Engineering`,
	239: `Pharmacology`,
	240: `Pharmacy`,
	241: `Philosophy`,
	242: `Photography`,
	243: `Photojournalism`,
	244: `Physical Education`,
	245: `Physical Therapy`,
	246: `Physician Assistant`,
	247: `Physics`,
	248: `Physiological Psychology`,
	249: `Piano`,
	250: `Planetary Science`,
	251: `Plant Pathology`,
	252: `Playwriting and Screenwriting`,
	253: `Political Communication`,
	254: `Political Science`,
	255: `Portuguese`,
	256: `Pre-Dentistry`,
	257: `Pre-Law`,
	258: `Pre-Medicine`,
	259: `Pre-Optometry`,
	260: `Pre-Seminary`,
	261: `Pre-Veterinary Medicine`,
	262: `Printmaking`,
	263: `Psychology`,
	264: `Public Administration`,
	265: `Public Health`,
	266: `Public Policy Analysis`,
	267: `Public Relations`,
	268: `Radio and Television`,
	269: `Radiologic Technology`,
	270: `Range Science and Management`,
	271: `Real Estate`,
	272: `Recording Arts Technology`,
	273: `Recreation Management`,
	274: `Rehabilitation Services`,
	275: `Religious Studies`,
	276: `Respiratory Therapy`,
	277: `Risk Management`,
	278: `Rural Sociology`,
	279: `Russian`,
	280: `Scandinavian Studies`,
	281: `Sculpture`,
	282: `Slavic Languages and Literatures`,
	283: `Social Psychology`,
	284: `Social Work`,
	285: `Sociology`,
	286: `Soil Science`,
	287: `Sound Engineering`,
	288: `South Asian Studies`,
	289: `Southeast Asia Studies`,
	290: `Spanish`,
	291: `Special Education`,
	292: `Speech Pathology`,
	293: `Sport and Leisure Studies`,
	294: `Sports Management`,
	295: `Statistics`,
	296: `Surveying`,
	297: `Sustainable Resource Management`,
	298: `Teacher Education`,
	299: `Teaching English as a Second Language`,
	300: `Technical Writing`,
	301: `Technology Education`,
	302: `Textile Engineering`,
	303: `Theatre`,
	304: `Theology`,
	305: `Tourism`,
	306: `Toxicology`,
	307: `Turfgrass Science`,
	308: `Urban Planning`,
	309: `Urban Studies`,
	310: `Visual Communication`,
	311: `Voice`,
	312: `Web Design`,
	313: `Webmaster and Web Management`,
	314: `Welding Engineering`,
	315: `Wildlife Management`,
	316: `Women's Studies`,
	317: `Youth Ministries`,
	318: `Zoology`,
	319: `Other`
}

const EnumSource = {
	INFO_SESSION: 'Info session',
	NETWORKING_SESSION: 'Networking session',
	COFFEE_CHAT: 'Coffee chat',
	OFFICE_VISIT: 'Office visit',
	LINKED_IN: 'LinkedIn',
	REFERRAL: 'Referral',
	OTHER: 'Other'
}


const EnumActivities = {
	COLD_EMAIL: 'Cold email',
	EMAIL_FOLLOW_UP: 'Email follow-up',
	PHONE_CALL: 'Phone call',
	COFFEE_CHAT: 'Coffee chat',
	RE_CONNECT: 'Re-connect',
	ASK_FOR_REFERRAL: 'Asked for referral',
	OTHER: 'Other'
}


export { EnumMonth, EnumIndustry, EnumDegreeType, EnumMajor, EnumSource,  EnumActivities }
